export default {
  lang_login_title:'Machine Advisor Cloud Platform',
  lang_login_code_getdes:'Send',
  lang_login_mobile_placeholder:'Enter 11-digit phone number',
  lang_login_code_des:'Verification Code',
  lang_login_mobilecode_placeholder:'Enter 4-digit verification code',
  lang_login_nameinputdes:'Username',
  lang_login_name_placeholder:'Enter username',
  lang_login_passdes:'Password',
  lang_login_pass_placeholder:'Enter password',
  lang_login_btndes:'Log in',
  lang_login_btnlogingdes:'Logging in...',
  lang_login_mobiledes:'Log in through verification code',
  lang_login_usernamedes:'Log in through username/password',

  lang_alarm_problem_alarm:'Fault Alarm',
  lang_alarm_filter:'Filter',
  lang_alarm_noalarm:'No Alarm',
  lang_alarm_nofilteralarm:'No Result',
  lang_alarm_highdes:'High',
  lang_alarm_midddes:'Middle',
  lang_alarm_lowdes:'Low',
  lang_alarm_states:'Status',
  lang_alarm_not_resolved:'Unremoved',
  lang_alarm_already_resolved:'Removed',
  lang_alarm_leveldes:'Level',
  lang_alarm_high_level:'High-level',
  lang_alarm_midd_level:'Middle-level',
  lang_alarm_low_level:'Low-level',
  lang_alarm_category:'Type',
  lang_alarm_position:'Location',
  lang_alarm_filterdes:'Filter Alarm',
  lang_alarm_midd_date:'YYYY-M-D',
  lang_alarm_power_factor:'Power Factor',
  lang_alarm_assetdes:'Asset',
  lang_alarm_setting_value:'Set Value',
  lang_alarm_type:'Type',
  lang_alarm_datas:'Data',
  lang_alarm_invalid_value:'Invalid Value',
  lang_alarm_problem_reason:'Fault Cause',
  lang_alarm_reason:'Cause',
  lang_alarm_detail:'Detail',
  lang_alarm_alarmdetail:'Alarm Detail',
  lang_alarm_reason0:'Fault Tripping',
  lang_alarm_reason1:'Long Time Delay Tripping',
  lang_alarm_reason2:'Short Time Delay Tripping',
  lang_alarm_reason3:'Instantaneous Tripping',
  lang_alarm_reason4:'Ground Fault',
  lang_alarm_reason5:'Leakage Protection',
  lang_alarm_reason6:'Other Types',
  lang_alarm_create:'Alarm occurs',
  lang_alarm_des0:'Alarm removed, on-site data is normal',
  lang_alarm_des1:'No permission, please contact the administrator',
  lang_alarm_des2:'Sorry, no permission to view this alarm',
  lang_alarm_create_ticket:'Create alarm ticket',
  lang_alarm_view_ticket:'View ticket',

  lang_common_finish:'Finish',
  lang_ticket_remove:'Delete',
  lang_ticket_customer_name:'Customer Name',
  lang_ticket_start_time:'Start Date',
  lang_ticket_end_time:'End Date',
  lang_ticket_please_choice:'Choose',
  lang_ticket_executer:'Executer',
  lang_ticket_input_detail:'Enter details',
  lang_ticket_ticket_tash:'Ticket Task',
  lang_ticket_scene:'On-site',
  lang_ticket_random:'Provisional',
  lang_ticket_ticket_type:'Ticket Type',
  lang_ticket_ticket_planning:'Plan Ticket',
  lang_ticket_ticket_alarm:'Alarm Ticket',
  lang_ticket_ticket_folow:'Provisional Ticket',
  lang_ticket_ticket_scene:'On-site Ticket',
  lang_ticket_save:'Save',
  lang_ticket_create_ticket:'Create ticket',
  lang_ticket_edit_ticket:'Edit ticket',
  lang_ticket_notice0:'No associated customer, please contact the administrator',
  lang_ticket_notice1:'No Asset',
  lang_ticket_more:'More',
  lang_ticket_notice2:'Unable to open this file',
  lang_ticket_input2:'Enter',
  lang_ticket_notice3:'Enter ticket task description',
  lang_ticket_last:'Past',
  lang_ticket_today:'Today',
  lang_ticket_future:'Future',
  lang_ticket_myticket:'My Ticket',
  lang_ticket_filter_ticket:'Filter ticket',
  lang_ticket_run_time:'Execution Time',
  lang_ticket_asset_position:'Asset Location',
  lang_ticket_start_time_format:'Start from {0}',//text = `${startTime} 开始`;
  lang_ticket_finish_time_format:'{0} to {1}',//${startTime} 至 ${endTime}

  lang_ticket_asset_range:'Asset Range',
  lang_ticket_task_des:'Task Description',
  lang_ticket_document:'Operation Document',
  lang_ticket_create_user:'Create User',
  lang_ticket_ticket_log:'Ticket Log',
  lang_ticket_start_execute:'Start Execution',
  lang_ticket_finish_ticket:'Finish Ticket',
  lang_ticket_ticket_edit:'Edit',
  lang_ticket_ticket_detail:'Ticket Detail',
  lang_ticket_not_start:'Unstarted',
  lang_ticket_going:'Executing',
  lang_ticket_finished:'Finished',
  lang_ticket_ticketid:'Ticket ID',
  lang_ticket_expired:'Overdue',
  lang_ticket_filter:'Filter ticket',
  lang_ticket_filter_result:'Filtering Result',
  lang_ticket_filter_noresult:'No Matching Ticket',
  lang_ticket_noticket:'No Ticket',
  lang_ticket_select_range:'Choose asset range first',
  lang_ticket_starttimeerr0:'Start date cannot be latter than end date',
  lang_ticket_remove_notice:'Ticket "{0}" will be deleted?',
  lang_ticket_cancel:'Cancel',
  lang_ticket_start_notice0:'Start executing ticket?',
  lang_ticket_finish_notice1:'Cannot edit or add log after ticket is finished, whether to finish?',
  lang_ticket_start_notice1:'Start executing, please add ticket log',
  lang_ticket_notice4:'Only log of executing ticket can be edited',
  lang_ticket_notice5:'Only creators can delete this log',
  lang_ticket_remove_log:'Delete this log?',
  lang_ticket_nolog:'No Ticket Log',
  lang_ticket_notice6:'Please enter log content or upload photos',
  lang_ticket_notice7:'Only creators can edit this log',
  lang_ticket_notice8:'Input ticket execution log',
  lang_ticket_select_customer:'Choose customer',
  lang_ticket_timeformat:'YYYY-M-D HH:mm:ss',
  lang_ticket_time:'Time:',
  lang_ticket_type:'Type:',
  lang_ticket_point:'Point:',
  lang_ticket_acture_value:'Actual Value:',
  lang_ticket_notice9:'Start executing ticket, refresh and view',
  lang_ticket_notice10:'You are not the executor, please contact the administrator',
  lang_ticket_notice11:'Sorry, the ticket is deleted',
  lang_ticket_notice12:'Sorry, no permission to view this ticket',
  lang_ticket_notice13:'Scan QR code on the device, \n and complete binding.',

  lang_commons_notice0:'无数据可显示，请在网页端进行配置',
  lang_commons_notice1:'无查看资产权限，联系管理员',
  lang_commons_yes:'是',
  lang_commons_no:'否',
  lang_commons_notice2:'未知错误',
  lang_commons_notice3:'加载失败，请检查您的网络设置',
  lang_commons_notice4:'登录失效，请重新登录',
  lang_commons_notice5:'发现新版本',
  lang_commons_notice6:'请更新至灯塔v{0}，马上体验！',
  lang_commons_notice7:'立即更新',
  lang_commons_notice8:'您的网络出现了问题，可能无法连接到系统',
  lang_commons_notice9:'再按一次退出应用',
  lang_commons_notice10:'您的网络已恢复',
  lang_commons_notice11:'加载中，请稍候...',
  lang_commons_notice12:'清空筛选条件',
  lang_commons_notice13:'将二维码放入框内，即可自动扫描',
  lang_commons_notice14:'请在手机的"设置"中，允许灯塔访问您的摄像头',
  lang_commons_notice15:'允许',
  lang_commons_notice16:'打开照相机',
  lang_commons_notice17:'从手机相册获取',
  lang_commons_notice18:'图片',
  lang_commons_notice19:'请在手机的"设置"中，允许灯塔访问您的相册',
  lang_commons_notice20:'最多只能选择{0}张图片',
  lang_commons_notice21:'拍照',
  lang_commons_notice22:'产品试用',
  lang_commons_notice23:'无附加文本',
  lang_commons_notice24:'添加',
  lang_commons_notice25:'报警',
  lang_commons_notice26:'工单',
  lang_commons_notice27:'已有账号，去登录',
  lang_commons_notice28:'立即查看',
  lang_commons_notice29:'无相关权限',

  lang_commons_see:'{0}\n是否查看？',

  lang_ticket_OK:'OK',

  lang_ticket_notice14:'您有一条新工单',
  lang_ticket_notice15:'您有一条新设备报警',


  lang_login_des0:'该手机号在系统内未注册',
  lang_login_des1:'该用户不存在',
  lang_login_des2:'密码输入有误',
  lang_login_des3:'验证码输入有误',
  lang_login_des4:'验证码已过期，请重新获取',

  lang_my_des0:'施耐德电气（中国）有限公司 版权所有',
  lang_my_des1:'施耐德',
  lang_my_des2:'下载新版本{0}',
  lang_my_des3:'(已为最新版本)',
  lang_my_des4:'版本信息',
  lang_my_des5:'关于',
  lang_my_des6:'灯塔',
  lang_my_des7:'当前版本',
  lang_my_des8:'版本',
  lang_my_des9:'删除这张图片吗？',
  lang_my_des10:'删除这个文件吗？',
  lang_my_des11:'添加照片',
  lang_my_des12:'提交',
  lang_my_des13:'意见反馈',
  lang_my_des14:'请输入您的问题或建议',
  lang_my_des15:'电话或邮箱，便于我们和您取得联系',
  lang_my_des16:'您对灯塔云平台的建议:',
  lang_my_des17:'您的联系方式（选填）',
  lang_my_des18:'修改昵称',
  lang_my_des19:'使用手机扫描',
  lang_my_des20:'即可立即下载灯塔APP',
  lang_my_des21:'二维码',
  lang_my_des22:'昵称',
  lang_my_des23:'APP二维码',
  lang_my_des24:'退出登录',

  lang_my_des25:'我的',
  lang_my_des26:'请输入您的问题或建议...',
  lang_my_des27:'您要退出这个账号吗？',
  lang_my_des28:'退出',
  lang_my_des29:'昵称不能为空',
  lang_my_des30:'提交中...',
  lang_my_des31:'反馈提交成功!',
  lang_my_des32:'绑定成功!',

  lang_asset_des0:'联系他/她',
  lang_asset_des1:'尚无任何资产可显示',
  lang_asset_des2:'扫一扫',
  lang_asset_des3:'绑定二维码',
  lang_asset_des4:'扫描结果',
  lang_asset_des5:'尚无任何资产可显示',
  lang_asset_des6:'暂未关联任何建筑，请联系管理员',
  lang_asset_des7:'选择设备',
  lang_asset_des8:'该建筑下无配电室和设备',
  lang_asset_des9:'结束时间不能小于开始的时间',
  lang_asset_des10:'时间选择范围不能超过一年',
  lang_asset_des11:'不能选择未来日期',
  lang_asset_des12:'查看',
  lang_asset_des13:'设备信息',
  lang_asset_des14:'数据监视',
  lang_asset_des15:'运维参数',
  lang_asset_des16:'运行指标',
  lang_asset_des17:'已绑定',
  lang_asset_des18:'网关离线',
  lang_asset_des19:'YYYY年MM月DD日',
  lang_asset_des20:'YYYY年MM月DD日 HH:mm',
  lang_asset_des21:'MM月DD日',
  lang_asset_des22:'YYYY年MM月',
  lang_asset_des23:'YYYY年',
  lang_asset_des24:'此时间段内无{0}',
  lang_asset_des25:'能耗数据',
  lang_asset_des26:'历史数据',
  lang_asset_des27:'不能选择未来日期',
  lang_asset_step_day:'天',
  lang_asset_step_hours:'小时',
  lang_asset_step_weeks:'周',
  lang_asset_step_month:'月',
  lang_asset_step_year:'年',
  lang_asset_des28:'图纸',
  lang_asset_des29:'没有图纸',
  lang_asset_des30:'输入现场日志',
  lang_asset_des31:'现场日志',
  lang_asset_des32:'无现场日志',
  lang_asset_:'变频与驱动',
  lang_asset_des33:'添加一张资产照片',
  lang_asset_des34:'维护历史',
  lang_asset_des35:'暂无维护历史纪录',

  lang_asset_des36:'次',//server
  lang_asset_des37:'平均运行频率',
  lang_asset_des38:'平均电机电流',
  lang_asset_des39:'平均节电率',
  lang_asset_des40:'瞬时节电率',
  lang_asset_des41:'累积运行时间',
  lang_asset_des42:'重故障次数',

  lang_asset_des43:'设备总称',
  lang_asset_des44:'设备类型',
  lang_asset_des45:'资产描述',
  lang_asset_des46:'出厂日期',
  lang_asset_des47:'设备厂家',
  lang_asset_des48:'资产编号',

  lang_asset_des49:'脱扣单元类型',//server
  lang_asset_des50:'设备参数',

  lang_asset_des51:'该型号的断路器不支持老化参数计算',
  lang_asset_des52:'环境参数配置不全，请检查断路器所在配电柜信息的【环境参数】',
  lang_asset_des53:'断路器负载率运行时间为无效值，请检查断路器的【维护参数】',
  lang_asset_des54:'断路器老化参数计算初始化异常',
  lang_asset_des55:'断路器老化参数计算出现异常',
  lang_asset_des56:'断路器触头磨损率为无效值，请检查断路器的【维护参数】',

  lang_asset_des57:'设备老化参数计算',
  lang_asset_des58:'A相电流最大需量',//server
  lang_asset_des59:'B相电流最大需量',//server
  lang_asset_des60:'C相电流最大需量',//server
  lang_asset_des61:'长延时保护电流',//server
  lang_asset_des62:'长延时保护电流(lr)设定',//server

  lang_asset_des63:'长延时保护电流(lr)为空',//?
  lang_asset_des64:'长延时保护电流(lr)为无效值',//?
  lang_asset_des65:'相电流最大需量',//server

  lang_asset_des66:'过大',
  lang_asset_des67:'过小',

  lang_asset_des67:'需量与保护定值比',
  lang_asset_des68:'保护设定值',

  lang_asset_des69:'型号',
  lang_asset_des70:'母排温度',
  lang_asset_des71:'柜内温度',
  lang_asset_des72:'柜内湿度',
  lang_asset_des73:'柜内粉尘浓度',
  lang_asset_des74:'环境数据',
  lang_asset_des75:'设备统计信息',

  lang_asset_des76:'零级',
  lang_asset_des77:'一级',
  lang_asset_des78:'二级',
  lang_asset_des79:'三级',
  lang_asset_des80:'四级',
  lang_asset_des81:'五级',
  lang_asset_des82:'生产线描述',
  lang_asset_des83:'现场描述',
  lang_asset_des84:'能耗统计',//server
  lang_asset_des85:'室内温度',
  lang_asset_des86:'室内湿度',
  lang_asset_des87:'室内粉尘浓度',

  lang_asset_des88:'统计信息',
  lang_asset_des89:'环境数据',
  lang_asset_des90:'维护负责人',
  lang_asset_des91:'无法识别与灯塔系统不相关的二维码，请确认后再试！',
  lang_asset_des92:'您扫的二维码不是灯塔资产二维码，请确认',

  //未知项，是否需要用英文？
  lang_asset_des93:'施耐德电气灯塔',
  lang_asset_des94:'您有报警，请查看!',
  lang_asset_des95:'报警已解除，请查看!',
  lang_asset_des96:'您有工单，请查看!',
  lang_asset_des97:'工单已完成，请查看!',
  lang_asset_des98:'/施耐德电气灯塔提示您设备报警\(([a-zA-Z0-9]*)\)，请及时检查响应/',
  lang_asset_des99:'/施耐德电气灯塔提示您设备报警\(([a-zA-Z0-9]*)\)已解除/',
  lang_asset_des100:'/施耐德电气灯塔提示您有新工单\(([a-zA-Z0-9]*)\)/',
  lang_asset_des101:'/施耐德电气灯塔通知您创建的工单\(([a-zA-Z0-9]*)\)/',

};
