export default {
  lang_login_title:'Machine Advisor',
  lang_login_code_getdes:'Send',
  lang_login_mobile_placeholder:'Enter 11-digit phone number',
  lang_login_code_des:'Code',
  lang_login_mobilecode_placeholder:'Enter 4-digit code',
  lang_login_nameinputdes:'User ID',
  lang_login_name_placeholder:'Enter username',
  lang_login_passdes:'Password',
  lang_login_pass_placeholder:'Enter password',
  lang_login_btndes:'Log in',
  lang_login_btnlogingdes:'Logging in...',
  lang_login_mobiledes:'Log in through verification code',
  lang_login_usernamedes:'Log in through username/password',

  lang_alarm_problem_alarm:'Fault Alarm',
  lang_alarm_filter:'Filter',
  lang_alarm_noalarm:'No Alarm',
  lang_alarm_nofilteralarm:'No Result',
  lang_alarm_highdes:'High',
  lang_alarm_midddes:'Medium',
  lang_alarm_lowdes:'Low',
  lang_alarm_states:'Status',
  lang_alarm_not_resolved:'Unremoved',
  lang_alarm_already_resolved:'Removed',
  lang_alarm_leveldes:'Level',
  lang_alarm_high_level:'High-level',
  lang_alarm_midd_level:'Middle-level',
  lang_alarm_low_level:'Low-level',
  lang_alarm_category:'Type',
  lang_alarm_position:'Location',
  lang_alarm_filterdes:'Filter Alarm',
  lang_alarm_midd_date:'YYYY-M-D',
  lang_alarm_power_factor:'功率因数',//'Power Factor',
  lang_alarm_assetdes:'Asset',
  lang_alarm_setting_value:'Set Value',
  lang_alarm_type:'Type',
  lang_alarm_datas:'Data',
  lang_alarm_invalid_value:'Invalid Value',
  lang_alarm_problem_reason:'Fault Cause',
  lang_alarm_reason:'Cause',
  lang_alarm_detail:'Detail',
  lang_alarm_alarmdetail:'Alarm Detail',
  lang_alarm_reason0:'Exceed Threshold',
  lang_alarm_reason1:'Deceed Threshold',
  lang_alarm_reason2:'Status 1 Alarm',
  lang_alarm_reason3:'Status 0 Alarm',
  lang_alarm_reason4:'Gateway Offline',
  lang_alarm_reason5:'Device Offline',
  lang_alarm_reason6:'Other Types',
  lang_alarm_create:'Alarm occurs',
  lang_alarm_des0:'Alarm removed, on-site data is normal',
  lang_alarm_des1:'No permission, please contact the administrator',
  lang_alarm_des2:'Sorry, no permission to view this alarm',
  lang_alarm_create_ticket:'Create alarm ticket',
  lang_alarm_view_ticket:'View ticket',

  lang_common_finish:'Done',
  lang_ticket_remove:'Delete',
  lang_ticket_customer_name:'Customer Name',
  lang_ticket_start_time:'Start Date',
  lang_ticket_end_time:'End Date',
  lang_ticket_please_choice:'Choose',
  lang_ticket_executer:'Executer',
  lang_ticket_input_detail:'Enter details',
  lang_ticket_ticket_tash:'Ticket Task',
  lang_ticket_scene:'On-site',
  lang_ticket_random:'Provisional',
  lang_ticket_ticket_type:'Ticket Type',
  lang_ticket_ticket_planning:'Plan Ticket',
  lang_ticket_ticket_alarm:'Alarm Ticket',
  lang_ticket_ticket_folow:'Provisional Ticket',
  lang_ticket_ticket_scene:'On-site Ticket',
  lang_ticket_save:'Save',
  lang_ticket_create_ticket:'Create ticket',
  lang_ticket_edit_ticket:'Edit ticket',
  lang_ticket_notice0:'No associated customer, please contact the administrator',
  lang_ticket_notice1:'No Asset',
  lang_ticket_more:'More',
  lang_ticket_notice2:'Unable to open this file',
  lang_ticket_input2:'Enter',
  lang_ticket_notice3:'Enter ticket task description',
  lang_ticket_last:'Past',
  lang_ticket_today:'Today',
  lang_ticket_future:'Future',
  lang_ticket_myticket:'My Ticket',
  lang_ticket_filter_ticket:'Filter ticket',
  lang_ticket_run_time:'Time',
  lang_ticket_asset_position:'Asset Location',
  lang_ticket_start_time_format:'Start from {0}',//text = `${startTime} 开始`;
  lang_ticket_finish_time_format:'{0} to {1}',//${startTime} 至 ${endTime}

  lang_ticket_asset_range:'Asset Range',
  lang_ticket_task_des:'Task Description',
  lang_ticket_document:'File',
  lang_ticket_create_user:'Creator',
  lang_ticket_ticket_log:'Ticket Log',
  lang_ticket_start_execute:'Start Execution',
  lang_ticket_finish_ticket:'Finish Ticket',
  lang_ticket_ticket_edit:'Edit',
  lang_ticket_ticket_detail:'Ticket Detail',
  lang_ticket_not_start:'Unstarted',
  lang_ticket_going:'Executing',
  lang_ticket_finished:'Finished',
  lang_ticket_ticketid:'Ticket ID',
  lang_ticket_expired:'Overdue',
  lang_ticket_filter:'Filter ticket',
  lang_ticket_filter_result:'Filtering Result',
  lang_ticket_filter_noresult:'No Matching Ticket',
  lang_ticket_noticket:'No Ticket',
  lang_ticket_select_range:'Choose asset range first',
  lang_ticket_starttimeerr0:'Start date cannot be latter than end date',
  lang_ticket_remove_notice:'Ticket "{0}" will be deleted?',
  lang_ticket_cancel:'Cancel',
  lang_ticket_start_notice0:'Start executing ticket?',
  lang_ticket_finish_notice1:'Cannot edit or add log after ticket is finished, whether to finish?',
  lang_ticket_start_notice1:'Start executing, please add ticket log',
  lang_ticket_notice4:'Only log of executing ticket can be edited',
  lang_ticket_notice5:'Only creators can delete this log',
  lang_ticket_remove_log:'Delete this log?',
  lang_ticket_nolog:'No Ticket Log',
  lang_ticket_notice6:'Please enter log content or upload photos',
  lang_ticket_notice7:'Only creators can edit this log',
  lang_ticket_notice8:'Input ticket execution log',
  lang_ticket_select_customer:'Choose customer',
  lang_ticket_timeformat:'YYYY-M-D HH:mm:ss',
  lang_ticket_time:'Time:',
  lang_ticket_type:'Type:',
  lang_ticket_point:'Point:',
  lang_ticket_acture_value:'Actual Value:',
  lang_ticket_notice9:'Start executing ticket, refresh and view',
  lang_ticket_notice10:'You are not the executor, please contact the administrator',
  lang_ticket_notice11:'Sorry, the ticket is deleted',
  lang_ticket_notice12:'Sorry, no permission to view this ticket',
  lang_ticket_notice13:'Scan QR code on the device, \n and complete binding.',

  lang_commons_notice0:'No data to display, please configure on the Web',
  lang_commons_notice1:'No permission to view the asset, please contact the administrator',
  lang_commons_yes:'Yes',
  lang_commons_no:'No',
  lang_commons_notice2:'Unknown Error',
  lang_commons_notice3:'Loading failed, please check your network settings',
  lang_commons_notice4:'Login expired, please sign in again',
  lang_commons_notice5:'New version discovered',
  lang_commons_notice6:'Please update to Machine Advisor v{0}, and experience now.',
  lang_commons_notice7:'Update immediately',
  lang_commons_notice8:'Network error, unable to connect to the system',
  lang_commons_notice9:'Click again to exit',
  lang_commons_notice10:'Your network has recovered',
  lang_commons_notice11:'Loading, please wait...',
  lang_commons_notice12:'Clear filters',
  lang_commons_notice13:'Align QR Code within frame to scan',
  lang_commons_notice14:'Allow machine advisor to access camera in the "Settings" of your phone',
  lang_commons_notice15:'Allow',
  lang_commons_notice16:'Open Camera',
  lang_commons_notice17:'Choose from Album',
  lang_commons_notice18:'Photo',
  lang_commons_notice19:'Allow machine advisor to access photos in the "Settings" of your phone',
  lang_commons_notice20:'The limit is {0} photos',
  lang_commons_notice21:'Camera',
  lang_commons_notice22:'Product Trial',
  lang_commons_notice23:'No Attachments',
  lang_commons_notice24:'Add',
  lang_commons_notice25:'Alarm',
  lang_commons_notice26:'Ticket',
  lang_commons_notice27:'Account already exists, go log in',
  lang_commons_notice28:'View Now',
  lang_commons_notice29:'No Permission',

  lang_commons_see:'{0}\n Whether to view？',

  lang_ticket_OK:'OK',

  lang_ticket_notice14:'You have a new ticket',
  lang_ticket_notice15:'You have a new device alarm',


  lang_login_des0:'Phone number not registered in the system',
  lang_login_des1:'User does not exist',
  lang_login_des2:'Wrong Password',
  lang_login_des3:'Wrong Code',
  lang_login_des4:'Code expired, please send again',

  lang_my_des0:'© Schneider Electric (China) Investment Co. Ltd.',
  lang_my_des1:'Schneider',
  lang_my_des2:'Download New Version {0}',
  lang_my_des3:'(Already The Latest Version)',
  lang_my_des4:'Version Information',
  lang_my_des5:'About',
  lang_my_des6:'Machine Advisor',
  lang_my_des7:'Current Version',
  lang_my_des8:'Version',
  lang_my_des9:'Delete this photo?',
  lang_my_des10:'Delete this file?',
  lang_my_des11:'Add photo',
  lang_my_des12:'Submit',
  lang_my_des13:'Feedback',
  lang_my_des14:'Input your question or suggestion',
  lang_my_des15:'Phone or email to contact you',
  lang_my_des16:'Your suggestion for Machine Advisor:',
  lang_my_des17:'Your Contact (Optional)',
  lang_my_des18:'Change Nickname',
  lang_my_des19:'Scan with your phone',
  lang_my_des20:'to download Machine Advisor APP',
  lang_my_des21:'QR Code',
  lang_my_des22:'Nickname',
  lang_my_des23:'APP QR Code',
  lang_my_des24:'Log out',

  lang_my_des25:'Me',
  lang_my_des26:'Input your question or suggestion...',
  lang_my_des27:'Log out of this account?',
  lang_my_des28:'Log out',
  lang_my_des29:'Nickname cannot be empty',
  lang_my_des30:'Submitting...',
  lang_my_des31:'Submitted.',
  lang_my_des32:'Bound successfully.',

  lang_asset_des0:'Contact him/her',
  lang_asset_des1:'No asset to display',
  lang_asset_des2:'Scan',
  lang_asset_des3:'Bind QR Code',
  lang_asset_des4:'Scanning Result',
  lang_asset_des5:'No asset to display',
  lang_asset_des6:'No associated building, please contact the administrator',
  lang_asset_des7:'Choose device',
  lang_asset_des8:'No switching room and device in this building',
  lang_asset_des9:'End time cannot be earlier than start time',
  lang_asset_des10:'Time range cannot exceed one year',
  lang_asset_des11:'Cannot choose a future date',
  lang_asset_des12:'View',
  lang_asset_des13:'Device Info',
  lang_asset_des14:'Data Monitoring',
  lang_asset_des15:'Parameter',
  lang_asset_des16:'Operation Indicator',
  lang_asset_des17:'Bound',
  lang_asset_des18:'Gateway Offline',
  lang_asset_des19:'YYYY-MM-DD',
  lang_asset_des20:'YYYY-MM-DD HH:mm',
  lang_asset_des21:'MM-DD',
  lang_asset_des22:'YYYY-MM',
  lang_asset_des23:'YYYY',
  lang_asset_des24:'No {0} during this period',
  lang_asset_des25:'Energy Consumption Data',
  lang_asset_des26:'History Data',
  lang_asset_des27:'Cannot choose a future date',
  lang_asset_step_day:'Day',
  lang_asset_step_hours:'Hour',
  lang_asset_step_weeks:'Week',
  lang_asset_step_month:'Month',
  lang_asset_step_year:'Year',
  lang_asset_des28:'Diagram',
  lang_asset_des29:'No Diagram',
  lang_asset_des30:'Input on-site log',
  lang_asset_des31:'On-site Log',
  lang_asset_des32:'No On-site Log',
  lang_asset_:'Variable Frequency and Drive',
  lang_asset_des33:'Add one asset photo',
  lang_asset_des34:'Maintenance History',
  lang_asset_des35:'No Maintenance History',

  lang_asset_des36:'Time(s)',//server
  lang_asset_des37:'Average Operating Frequency',
  lang_asset_des38:'Average Motor Current',
  lang_asset_des39:'Average Power Saving Rate',
  lang_asset_des40:'Instant Power Saving Rate',
  lang_asset_des41:'Accumulated Runtime',
  lang_asset_des42:'Number of Serious Faults',

  lang_asset_des43:'Device Full Name',
  lang_asset_des44:'Device Type',
  lang_asset_des45:'Asset Description',
  lang_asset_des46:'Ex-factory Date',
  lang_asset_des47:'Device Manufacturer',
  lang_asset_des48:'Asset Number',

  lang_asset_des49:'Tripping Unit Type',//server
  lang_asset_des50:'Device Parameter',

  lang_asset_des51:'This breaker model does not support aging parameter calculation',
  lang_asset_des52:'Environment parameters are incomplete, please check [environment parameter] of the breaker switchboard',
  lang_asset_des53:'Load rate runtime is invalid, please check [maintenance parameter] of the breaker',
  lang_asset_des54:'Abnormal initialization of breaker aging parameter calculation',
  lang_asset_des55:'Abnormal breaker aging parameter calculation',
  lang_asset_des56:'Contact wear rate is invalid, please check [maintenance parameter] of the breaker',

  lang_asset_des57:'Device Aging Parameter Calculation',
  lang_asset_des58:'Max Demand of Current A',//server
  lang_asset_des59:'Max Demand of Current B',//server
  lang_asset_des60:'Max Demand of Current C',//server
  lang_asset_des61:'Ir',//server
  lang_asset_des62:'Ir is set too small',

  lang_asset_des63:'Ir is empty',
  lang_asset_des64:'Ir is invalid',
  lang_asset_des65:'Max Demand of Current',//server

  lang_asset_des66:'Ir is set too big',
  lang_asset_des670:'Too Small',

  lang_asset_des67:'Demand to Ir Ratio',
  lang_asset_des68:'Protection Set Value',

  lang_asset_des69:'Model',
  lang_asset_des70:'Busbar Temperature',
  lang_asset_des71:'Inboard Temperature',
  lang_asset_des72:'Inboard Humidity',
  lang_asset_des73:'Inboard Dust Level',
  lang_asset_des74:'Environment Data',
  lang_asset_des75:'Device Statistics',

  lang_asset_des76:'Level 0',
  lang_asset_des77:'Level 1',
  lang_asset_des78:'Level 2',
  lang_asset_des79:'Level 3',
  lang_asset_des80:'Level 4',
  lang_asset_des81:'Level 5',
  lang_asset_des82:'Production Line Description',
  lang_asset_des83:'On-site Description',
  lang_asset_des84:'Energy Consumption Statistics',//server
  lang_asset_des85:'Indoor Temperature',
  lang_asset_des86:'Indoor Humidity',
  lang_asset_des87:'Indoor Dust Level',

  lang_asset_des88:'Statistics',
  lang_asset_des89:'Environment Data',
  lang_asset_des90:'Maintenance Administrator',
  lang_asset_des91:'Unable to recognize QR code irrelevant to Machine Advisor, please confirm and try again.',
  lang_asset_des92:'The QR code you scanned is irrelevant to Machine Advisor asset, please confirm',

  //未知项，是否需要用英文？
  lang_asset_des93:'Schneider Electric Machine Advisor',
  lang_asset_des94:'You have an alarm, please check.',
  lang_asset_des95:'Alarm removed, please check.',
  lang_asset_des96:'You have a ticket, please check.',
  lang_asset_des97:'Ticket completed, please check.',
  lang_asset_des98:'/Schneider Electric Machine Advisor reminds you of device alarm\(([a-zA-Z0-9]*)\), please check/',
  lang_asset_des99:'/Schneider Electric Machine Advisor reminds you of device alarm\(([a-zA-Z0-9]*)\) removed/',
  lang_asset_des100:'/Schneider Electric Machine Advisor reminds you of a new ticket\(([a-zA-Z0-9]*)\)/',
  lang_asset_des101:'/Schneider Electric Machine Advisor reminds you of created ticket\(([a-zA-Z0-9]*)\)/',

};
