export default {
  lang_login_title:'灯塔云平台',
  lang_login_code_getdes:'获取',
  lang_login_mobile_placeholder:'请填写11位手机号码',
  lang_login_code_des:'验证码',
  lang_login_mobilecode_placeholder:'请填写4位验证码',
  lang_login_nameinputdes:'用户名',
  lang_login_name_placeholder:'请填写用户名',
  lang_login_passdes:'密码',
  lang_login_pass_placeholder:'请填写密码',
  lang_login_btndes:'登录',
  lang_login_btnlogingdes:'登录中...',
  lang_login_mobiledes:'手机验证码登录',
  lang_login_usernamedes:'用户名密码登录',

  lang_alarm_problem_alarm:'故障报警',
  lang_alarm_filter:'筛选',
  lang_alarm_noalarm:'暂无报警',
  lang_alarm_nofilteralarm:'没有符合筛选条件的报警',
  lang_alarm_highdes:'高',
  lang_alarm_midddes:'中',
  lang_alarm_lowdes:'低',
  lang_alarm_states:'状态',
  lang_alarm_not_resolved:'未解除',
  lang_alarm_already_resolved:'已解除',
  lang_alarm_leveldes:'级别',
  lang_alarm_high_level:'高级',
  lang_alarm_midd_level:'中级',
  lang_alarm_low_level:'低级',
  lang_alarm_category:'类别',
  lang_alarm_position:'位置',
  lang_alarm_filterdes:'报警筛选',
  lang_alarm_midd_date:'YYYY年M月D日',

  lang_alarm_power_factor:'功率因数',
  lang_alarm_assetdes:'资产',
  lang_alarm_setting_value:'设定值',
  lang_alarm_type:'类型',
  lang_alarm_datas:'数据',
  lang_alarm_invalid_value:'无效值',
  lang_alarm_problem_reason:'故障原因',
  lang_alarm_reason:'原因',
  lang_alarm_detail:'详情',
  lang_alarm_alarmdetail:'报警详情',

  lang_alarm_reason0:'故障跳闸',
  lang_alarm_reason1:'长延时脱扣',
  lang_alarm_reason2:'短延时脱扣',
  lang_alarm_reason3:'瞬动脱扣',
  lang_alarm_reason4:'接地故障',
  lang_alarm_reason5:'漏电保护',
  lang_alarm_reason6:'其他类别',
  lang_alarm_create:'发生报警',
  lang_alarm_des0:'报警已解除，现场数据已正常',
  lang_alarm_des1:'您没有这一项的操作权限，请联系系统管理员',
  lang_alarm_des2:'抱歉，您没有查看该报警权限',



  lang_alarm_:'',

};
